services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334

  neo4j:
    image: neo4j:5.13
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/qBicC1zbW-Brmtj-GbCILMfyGkKaKwA25d2JaMfxKGA
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*,apoc.met.*'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,apoc.meta.*'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_use_neo4j_config: 'true'

